### ISSUE TITLE
Create

### ISSUE THREAD

**Issue by DiaoDeBuDeLiao** [CSCI-GA-2820-FA22-001/products#4]
**As a** User
 **I need** to add a new product to platform
 **So that** the platform will have the product record
   
 ### Details and Assumptions
 * Assign an unique ID to the product
 * Product details (Name, Price, Picture)
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given a new product information
 When a user want to create a new product to platform with product information
 Then write product into database
 ```

**Comment by marfa0414** [comment]
We should uniform the tile like create the product
