### ISSUE TITLE
Product Validation

### ISSUE THREAD

**Issue by DiaoDeBuDeLiao** [CSCI-GA-2820-FA22-001/products#9]
**As a** product owner
 **I need** to verify the product information 
 **So that** the product information is valid and will not cause error to the database
   
 ### Details and Assumptions
 * Product details(ID, Name, Price, Description, Picture)
 * Valid ID should be unique in database
 * Valid Name should be capitalized and within 20 chars
 * Valid Price should >= 0
 * Valid Description should has length >= 1
 * Valid Picture should not be empty
 * If anything invalid, return False. Else insert product into database and return True.
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given a product information
 When a new product is created or edited and before the information is written into the database
 Then check if it has a unique ID, a valid name, a valid price, a valid description, and a valid picture. 
 ```

**Comment by ElioZhou** [comment]
The `details and assumptions` section could be more specific like what's the invalid input format.
